name: over_my_Dead_body
version: ${project.version}
main: kun.minecraft_plugin.dead_body.Dead_body
api-version: 1.15
description: "一度死亡した場所は、危険地帯となり、入れなくなるプラグインです。\
危険地帯にサバイバルモードまたはアドベンチャーモードのプレイヤーが侵入した場合、即死します。"
author: "kasumi-29 (kasumigaura)"
website: "https://github.com/kasumi-29/over_my_Dead_body"

commands:
  set-safezone:
    description: "安全地帯を作成します"
    permission: op
    usage: "/<command>"
  save-locate:
    description: "死亡地点、安全地帯に関する情報をファイルに書き出します"
    permission: op
    usage: "/<command>"
  load-locate:
    description: "死亡地点、安全地帯に関する情報をファイルから読み込みます"
    permission: op
    usage: "/<command>"
  info-locate:
    description: "初期スポーン位置などの情報を表示します"
    permission: op
    usage: "/<command>"