name: over_my_Dead_body
version: ${project.version}
main: kun.minecraft_plugin.dead_body.Dead_body
api-version: 1.15

commands:
  set-safezone:
    description: "安全地帯を作成します"
    permission: op
    usage: "/<command>"
  save-locate:
    description: "死亡地点、安全地帯に関する情報をファイルに書き出します"
    permission: op
    usage: "/<command>"
  load-locate:
    description: "死亡地点、安全地帯に関する情報をファイルから読み込みます"
    permission: op
    usage: "/<command>"
