name: over_my_Dead_body
version: ${project.version}
main: kun.minecraft_plugin.dead_body.Dead_body
api-version: 1.15

commands:
  set-safezone:
    description: "安全地帯を作成します"
    permission: op
    usage: "/<command>"
